### ISSUE TITLE
The L-bar mount details?

### ISSUE THREAD

**Issue by zenny** [bwann/homelab#1]
@bwann Thanks for sharing this nifty setup. I could not find the following info in https://github.com/bwann/homelab/blob/master/blade.md:

1. What kind of L-bar did you use to hold the motherboard? 

2. How is the L-bar hooked to the Helmer sides? Any specific screws or welded?

3. How is the motherboard mounted on the L-bar?

4. How is the network arranged?

Thanks!

**Comment by bwann** [comment]
The L-bar does not hold the motherboard, it just reinforces the acrylic sheet to avoid sagging over time with heat.

The motherboard is mounted on long #8 screws with three nuts, run the screw through the bottom of the acrylic, place a nut to secure the screw to the sheet, another nut a few mm up to on which the motherboard will stand off on, and another nut after the motherboard is placed. This is a crude but effective standoff.

The extra L-bar to create extra blade positions is attached to the Helmer sides with #8 metal screws.

Network can be arranged however you want, I ran thin, flat ethernet cables from each motherboard to a switch. The flat cables were much less bulky than standard cat 5 cable

**Comment by zenny** [comment]
@bwann Thanks for your inputs.

> The L-bar does not hold the motherboard, it just reinforces the acrylic sheet to avoid sagging over time with heat.

Is there any reason why you chose not to use the Helmer drawer base-sheets to hold the blades instead?

> 
> The motherboard is mounted on long #8 screws with three nuts, run the screw through the bottom of the acrylic, place a nut to secure the screw to the sheet, another nut a few mm up to on which the motherboard will stand off on, and another nut after the motherboard is placed. This is a crude but effective standoff.

Great explanation! :+1: 

> 
> The extra L-bar to create extra blade positions is attached to the Helmer sides with #8 metal screws.

Yep this is what I am interested in. How do you screwed those L-bars to the Helmer sides? Which screws?

> 
> Network can be arranged however you want, I ran thin, flat ethernet cables from each motherboard to a switch. The flat cables were much less bulky than standard cat 5 cable

Yes, the flat cables looks the best arrangements! Thanks!

**Comment by bwann** [comment]
You could use the Helmer drawer sheets, in fact I did use one to mount the power supply and switches on.  If you just wanted a 5 motherboard system you could use them, but for any more you'd need to supplement with something else. For consistency I just decided to use acrylic sheets for all the motherboards.

Use whatever metal screws you want to screw the L-bars into the Helmer sides, as long as they're relatively low profile. As described in the doc I used #8 1/2" metal screws with a pre-drilled pilot hole. Self-tapping metal screws would work as well.
